# Loading dataset

In [1]:
import pandas as pd

In [2]:
train_data = pd.read_csv('C:..........reetu\\Springboard course\\Project 2\\train1.csv')  
test_data = pd.read_csv('C:\\.........\\reetu\\Springboard course\\Project 2\\test.csv') 


# Converting json format  
(#https://pythonexamples.org/python-csv-to-json/) 

In [9]:
import csv 
import json 

def csv_to_json(csvFilePath, jsonFilePath):
    jsonArray = []
      
    #read csv file
    with open(csvFilePath, encoding='utf-8') as csvf: 
        #load csv file data using csv library's dictionary reader
        csvReader = csv.DictReader(csvf) 

        #convert each csv row into python dict
        for row in csvReader: 
            #add this python dict to json array
            jsonArray.append(row)
  
    #convert python jsonArray to JSON String and write to file
    with open(jsonFilePath, 'w', encoding='utf-8') as jsonf: 
        jsonString = json.dumps(jsonArray, indent=4)
        jsonf.write(jsonString)
    #return jsonString


In [10]:
csvFilePath = r'C:\\Users\\vishd\\Desktop\\reetu\\Springboard course\\Project 2\\train1.csv'
jsonFilePath = r'C:\\Users\\vishd\\Desktop\\reetu\\Springboard course\\Project 2\\train1.json'
jsonFilePath_train = csv_to_json(csvFilePath, jsonFilePath)

# from test.csv to test.json

In [11]:
csvFilePath = r'C:\\Users\\vishd\\Desktop\\reetu\\Springboard course\\Project 2\\test.csv'
jsonFilePath = r'C:\\Users\\vishd\\Desktop\\reetu\\Springboard course\\Project 2\\test.json'
jsonFilePath_test = csv_to_json(csvFilePath, jsonFilePath)

# Preprocessing data

In [12]:
import json

def read_json(jsonFilePath):
    with open(jsonFilePath, 'rb') as f:
        data_dict = json.load(f)

    contexts = []
    questions = []
    answers = []
    answer_start = []
    for group in data_dict:
        groupKeys = group.keys()
        #print(groupKeys)
        if 'context' in groupKeys:
            contexts.append(group['context'])
        if 'question' in groupKeys:
            questions.append(group['question'])
        if 'answer_start' in groupKeys:
            answer_start.append(group['answer_start'])
        if 'answer_text' in groupKeys:
            answers.append(group['answer_text'])
    
    return contexts, questions, answers, answer_start

In [13]:
train_contexts, train_questions, train_answers, train_answer_start = read_json('C:\\Users\\vishd\\Desktop\\reetu\\Springboard course\\Project 2\\train1.json')
test_contexts, test_questions, test_answers, test_answer_start= read_json('C:\\Users\\vishd\\Desktop\\reetu\\Springboard course\\Project 2\\test.json')

In [14]:
#print(train_contexts[0])
print(test_contexts[0])

ज्वाला गुट्टा (जन्म: 7 सितंबर 1983; वर्धा, महाराष्ट्र) एक भारतीय बैडमिंटन खिलाडी हैं। 
 प्रारंभिक जीवन 
ज्वाला गुट्टा का जन्म 7 सितंबर 1983 को वर्धा, महाराष्ट्र में हुआ था। उनके पिता एम. क्रांति तेलुगु और मां येलन चीन से हैं। उनकी मां येलन गुट्टा पहली बार 1977 में अपने दादा जी के साथ भारत आई थीं। ज्वाला गुट्टा की प्रारंभिक पढ़ाई हैदराबाद से हुई और यहीं से उन्होंने बैडमिंटन खेलना भी शुरू किया। 
 कॅरियर 
10 साल की उम्र से ही ज्वाला गुट्टा ने एस.एम. आरिफ से ट्रेनिंग लेना शुरू कर दिया था। एस.एम. आरिफ भारत के जाने माने खेल प्रशिक्षक हैं जिन्हें द्रोणाचार्य अवार्ड से सम्मानित किया गया है। पहली बार 13 साल की उम्र में उन्होंने मिनी नेशनल बैडमिंटन चैंपियनशिप जीती थी। साल 2000 में ज्वाला गुट्टा ने 17 साल की उम्र में जूनियर नेशनल बैडमिंटन चैंपियनशिप जीती। इसी साल उन्होंने श्रुति कुरियन के साथ डबल्स में जोड़ी बनाते हुए महिलाओं के डबल्स जूनियर नेशनल बैडमिंटन चैंपियनशिप और सीनियर नेशनल बैडमिंटन चैंपियनशिप में जीत हासिल की। श्रुति कुरियन के साथ उनकी जोड़ी काफी लंबे समय तक चली। 2002 से 2008 तक लगातार 

In [15]:
print(train_questions[0])
print(test_questions[0])

மனித உடலில் எத்தனை எலும்புகள் உள்ளன?
ज्वाला गुट्टा की माँ का नाम क्या है


In [16]:
print(type(len(train_answers[0])))
#print(train_answers[0])

print(train_answers[0])

<class 'int'>
206


In [17]:
print(train_answer_start[0])   # 55

53


In [18]:
print(type(train_answer_start[0]))
print(len(train_answer_start[0]))
print(train_answer_start[0])

<class 'str'>
2
53


# Finding end value of end answer text
find the start and end of our answer within the context — so we need to add an 'answer_end' value too:

In [19]:
# had index error: solved by https://www.stechies.com/typeerror-slice-indices-must-integers-none-have-index-metho/#:~:text=slice%20indices%20must%20be%20integers%20or%20None%20or,provide%20value%20other%20than%20an%20integer%20to%20it.

# Encoding

This concatenated version is stored within the input_ids attribute of our Encoding object. the data is stored as BERT-readable token IDs.

In [20]:
from transformers import DistilBertTokenizerFast
# initialize the tokenizer
tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')
# tokenize
train_encodings = tokenizer(train_contexts, train_questions, truncation=True, padding=True)
test_encodings = tokenizer(test_contexts, test_questions, truncation=True, padding=True)

In [21]:
tokenizer.decode(train_encodings['input_ids'][0])

'[CLS] [UNK] [UNK] வளரநத மனிதனுடைய [UNK] பினவரும 206 ( [UNK] [UNK] பகுதிகளாகக கருதபபடடால 208 ) [UNK] [UNK] [UNK]. [UNK] [UNK] [UNK] [UNK] [UNK] [UNK]. [UNK], மிகக [UNK] [UNK] மனிதரகளில, [UNK] மேலதிக விலா [UNK] ( [UNK] ) [UNK] [UNK] மேலதிகமான [UNK] [UNK] [UNK] ; [UNK] சில [UNK] தனி [UNK] கருதாவிடின, [UNK] [UNK] [UNK] ; [UNK] ( 3 - 5 ) குயிலலகு [UNK] சேரநது 26 [UNK] [UNK] 33 [UNK] கருதபபடலாம. மனித [UNK] 22 [UNK] ( காதுச [UNK] தவிர ) [UNK] ; [UNK] [UNK] [UNK] ( cranium ) [UNK] 14 முக [UNK] ( facial bones ) பிரிககபபடடுளளன. ( தடிதத [UNK] [UNK] படததில [UNK] [UNK] [UNK]. ) [UNK] [UNK] ( 8 ) 1 [UNK] ( frontal bone ) 2 [UNK] ( parietal bone ) ( 2 ) 3 [UNK] ( temporal bone ) ( 2 ) 4 பிடர [UNK] ( occipital bone ) [UNK] [UNK] ( sphenoid bone ) [UNK] ( ethmoid bone ) முக [UNK] ( 14 ) 7 [UNK] [UNK] ( mandible ) 6 [UNK] [UNK] ( maxilla ) ( 2 ) [UNK] ( palatine bone ) ( 2 ) 5 கனன [UNK] ( zygomatic bone ) ( 2 ) 9 நாசி [UNK] ( nasal bone ) ( 2 ) [UNK] [UNK] ( lacrimal bone ) ( 2 ) [UNK] சுவர [UNK] ( vom

In [22]:
train_encodings.keys()

dict_keys(['input_ids', 'attention_mask'])

In [23]:
print('The input has a total of {:} tokens.'.format(len(train_encodings)))

The input has a total of 2 tokens.


# Initializing the Dataset

In [24]:
def add_end_idx(answers, contexts, answer_start, encodings):
    answers_end = []
    answers_start = []
    
    start_positions = []
    end_positions = []
    # loop through each answer-context pair
    for answer, context, ans_start in zip(answers, contexts, answer_start):
        answers_start.append(ans_start)
 
        # gold_text: expected answer to find in context
        gold_text = answer # len(answers)                                              
   
        # changing the type from str to int
        start_idx = int(ans_start)
        #print(start_idx)
        
        # finding end index by adding len of goldtext to start index
        end_idx = start_idx + len(gold_text)
        #print(end_idx)
        
        # sometimes answers are off by a character or two
        if context[start_idx:end_idx] == gold_text:
            # if the answer is not off :)
            #print('in')
            answers_end.append(end_idx)
            #answers_end + end_idx
        else:
            #print('out')
            # this means the answer is off by 1-2 tokens
            for n in [1, 2]:
                if context[start_idx-n:end_idx-n] == gold_text:
                    answers_start = start_idx - n
                    print(end_idx - n)
                    answers_end.append(end_idx - n)
                   # answers_end + (end_idx - n)
        #Breaking out of loop after first iteration. Remove below line for complete processing
        #print('ans_start', answers_start)
        #break
     
    for i in range(len(answers_start)):
      
        start_positions.append(encodings.char_to_token(i, int(answers_start[i]))) 
        end_positions.append(encodings.char_to_token(i, int(answers_end[i])))
       
        # if start position is None, the answer passage has been truncated
        if start_positions[-1] is None:
            start_positions[-1] = tokenizer.model_max_length
        # end position cannot be found, char_to_token found space, so shift position until found
        shift = 1
        while end_positions[-1] is None:
            end_positions[-1] = encodings.char_to_token(i, int(answers_end[i] - shift))
            shift += 1
    # update our encodings object with the new token-based start/end positions
    encodings.update({'start_positions': start_positions, 'end_positions': end_positions})
       
        # append start/end token position using char_to_token method
    #encodings.update({'start_positions': start_positions, 'end_positions': end_positions})
        #print(start_positions)
    return answers_end, start_positions,end_positions

In [25]:
# and apply the function to our two answer lists
answers_end, start_positions, end_positions = add_end_idx(train_answers, train_contexts, train_answer_start, train_encodings)
#print(start_positions)
#print('-----------------------------------------------------')
#print(end_positions)

In [26]:
import torch

class Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings):
        self.encodings = encodings

    def __getitem__(self, idx):
        return {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}

    def __len__(self):
        return len(self.encodings.input_ids)


In [28]:
# build datasets for both our train and test sets
train_dataset = Dataset(train_encodings)
test_dataset = Dataset(test_encodings)
print(test_dataset[0])

{'input_ids': tensor([  101,  1319, 29871, 29876, 29870, 29876,  1317, 29856, 29856, 29876,
         1006,  1319, 29863, 29867,  1024,  1021,  1338, 29877, 29859, 29865,
        29869,  3172,  1025,  1335, 29869, 29862, 29876,  1010,  1331, 29875,
        29876, 29869, 29876, 29873, 29856, 29869,  1007,  1314, 29851,  1330,
        29876, 29869, 29859, 29878, 29868,  1329, 29857, 29867, 29877, 29856,
        29863,  1316, 29877, 29870, 29876, 29857, 29878,  1339,  1344,  1328,
        29869, 29876, 29869, 29866, 29877, 29851,  1319, 29878, 29871, 29863,
         1319, 29871, 29876, 29870, 29876,  1317, 29856, 29856, 29876,  1315,
        29876,  1319, 29863, 29867,  1021,  1338, 29877, 29859, 29865, 29869,
         3172,  1315, 29879,  1335, 29869, 29862, 29876,  1010,  1331, 29875,
        29876, 29869, 29876, 29873, 29856, 29869,  1331,  1339, 29848,  1324,
        29876,  1344,  1313, 29863, 29851,  1328, 29877, 29859, 29876,  1314,
        29867,  1012,  1315, 29869, 29876, 29859, 

# Fine-Tuning
Our data is ready for the model. we need to set the PyTorch environment, initialize the DataLoader which we will be using to load data during training — and finally, begin fine-tuning our model:

In [29]:
from transformers import DistilBertTokenizer, DistilBertForQuestionAnswering
import torch

In [30]:
model = DistilBertForQuestionAnswering.from_pretrained('distilbert-base-uncased')

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertForQuestionAnswering: ['vocab_transform.weight', 'vocab_transform.bias', 'vocab_layer_norm.weight', 'vocab_layer_norm.bias', 'vocab_projector.weight', 'vocab_projector.bias']
- This IS expected if you are initializing DistilBertForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForQuestionAnswering were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['qa_outputs.weight', 'qa_outputs.bias']
You should probably TRAIN this mode

In [74]:
from torch.utils.data import DataLoader
from transformers import AdamW
from tqdm import tqdm

# setup GPU/CPU
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
# move model over to detected device
model.to(device)
# activate training mode of model
model.train()
# initialize adam optimizer with weight decay (reduces chance of overfitting)
optim = AdamW(model.parameters(), lr=5e-5)

# initialize data loader for training data
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)

for epoch in range(3):
    # set model to train mode
    model.train()
    # setup loop (we use tqdm for the progress bar)
    loop = tqdm(train_loader, leave=True)
    for batch in loop:
        # initialize calculated gradients (from prev step)
        optim.zero_grad()
        # pull all the tensor batches required for training
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        start_positions = batch['start_positions'].to(device)
        end_positions = batch['end_positions'].to(device)
        # train model on batch and return outputs (incl. loss)
        outputs = model(input_ids, attention_mask=attention_mask,
                        start_positions=start_positions,
                        end_positions=end_positions)
        # extract loss
        loss = outputs[0]
        # calculate loss for every parameter that needs grad update
        loss.backward()
        # update parameters
        optim.step()
        # print relevant info to progress bar
        loop.set_description(f'Epoch {epoch}')
        loop.set_postfix(loss=loss.item())

Epoch 2: 100%|███████████████████████████████████████████████████████████████| 70/70 [48:55<00:00, 34.89s/it, loss=2.5]


# Saving Model

In [75]:
model_path = 'C:\\Users\\vishd\\Desktop\\reetu\\Springboard course\\Project 2\\distilbert-custom'
model.save_pretrained(model_path)
tokenizer.save_pretrained(model_path)

('C:\\Users\\vishd\\Desktop\\reetu\\Springboard course\\Project 2\\distilbert-custom\\tokenizer_config.json',
 'C:\\Users\\vishd\\Desktop\\reetu\\Springboard course\\Project 2\\distilbert-custom\\special_tokens_map.json',
 'C:\\Users\\vishd\\Desktop\\reetu\\Springboard course\\Project 2\\distilbert-custom\\vocab.txt',
 'C:\\Users\\vishd\\Desktop\\reetu\\Springboard course\\Project 2\\distilbert-custom\\added_tokens.json')

# Reloading model

In [76]:
model_path = 'C:\\Users\\vishd\\Desktop\\reetu\\Springboard course\\Project 2\\distilbert-custom' 
#model_path = 'C:\\Users\\vishd\\Desktop\\reetu\\Springboard course\\Project 2\\distilbert-custom'
model = DistilBertForQuestionAnswering.from_pretrained(model_path)
tokenizer = DistilBertTokenizerFast.from_pretrained(model_path)

# Extracting the start and end token position 

In [77]:
#we can access the start_logits and end_logits tensors and perform an argmax function like so:

In [78]:
start_pred = torch.argmax(outputs['start_logits'], dim=1)
print(start_pred)
end_pred = torch.argmax(outputs['end_logits'], dim=1)
print(end_pred)

tensor([  1,  56,  89,   1,   2,  70,   1,   1, 410,   1])
tensor([491, 504, 495, 468, 468, 489,  14,   8, 485,   8])


# Testing Model

# Accuracy
The simplest metric we can measure here is accuracy — more specifically known as exact match (EM).
To calculate the EM of each batch, we take the sum of the number of matches per batch — and divide by the total. We do this with PyTorch like so:

In [86]:
acc = start_pred.sum() / len(start_pred)
print(acc)

tensor(69.8000)


In [91]:
start_true = batch['start_positions'].to(device)
print(start_true)
        #start_positions = batch['start_positions'].to(device)
end_true = batch['end_positions'].to(device)
print(end_true)
        # make predictions
start_pred = torch.argmax(outputs['start_logits'], dim=1)
print(start_pred)
end_pred = torch.argmax(outputs['end_logits'], dim=1)
print(end_pred)
acc = []
acc.append(((start_pred == start_true).sum()/len(start_pred)).item())
acc.append(((end_pred == end_true).sum()/len(end_pred)).item())
acc = sum(acc)/len(acc)
print(acc)

tensor([ 14, 408,  25, 235, 512, 512,   1, 104,  32, 512])
tensor([ 17, 418,  31, 242, 493, 481,   6, 104,  40, 486])
tensor([ 14,  23,  25, 235,   1,  20,  72, 164,  32, 112])
tensor([ 17,  31,  24, 475, 493, 481, 490, 104,  40, 486])
0.5000000149011612


In [80]:
from torch.utils.data import DataLoader
from transformers import AdamW
from tqdm import tqdm

# setup GPU/CPU
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
# move model over to detected device
model.to(device)
# activate training mode of model
model.train()
# initialize adam optimizer with weight decay (reduces chance of overfitting)
optim = AdamW(model.parameters(), lr=5e-5)

# switch model out of training mode
model.eval()
# initialize testing set data loader
test_loader = DataLoader(train_dataset, batch_size=16)
# initialize list to store accuracies
acc = []
# loop through batches
for batch in test_loader:
    # we don't need to calculate gradients as we're not training
    with torch.no_grad():
        # pull batched items from loader
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        # we will use true positions for accuracy calc
        start_true = batch['start_positions'].to(device)
        #start_positions = batch['start_positions'].to(device)
        end_true = batch['end_positions'].to(device)
        # make predictions
        outputs = model(input_ids, attention_mask=attention_mask)
        # pull prediction tensors out and argmax to get predicted tokens
        start_pred = torch.argmax(outputs['start_logits'], dim=1)
        end_pred = torch.argmax(outputs['end_logits'], dim=1)
        # calculate accuracy for both and append to accuracy list
        acc.append(((start_pred == start_true).sum()/len(start_pred)).item())
        acc.append(((end_pred == end_true).sum()/len(end_pred)).item())
# calculate average accuracy in total
acc = sum(acc)/len(acc)

In [81]:
print(acc)

0.4959821430700166


In [288]:
#https://careerkarma.com/blog/python-typeerror-str-object-cannot-be-interpreted-as-an-integer/
#https://careerkarma.com/blog/python-valueerror-invalid-literal-for-int-with-base-10/#:~:text=The%20Python%20ValueError%3A%20invalid%20literal%20for%20int%20%28%29,%28%29%20to%20convert%20your%20number%20to%20an%20integer.


In [ ]:
#https://towardsdatascience.com/how-to-fine-tune-a-q-a-transformer-86f91ec92997
#https://huggingface.co/bert-base-multilingual-uncased